=== yagofl02/LDM/xml Tema 1/Banco.dtd
<!ELEMENT banco (cuentas,clientes,clientes_cuentas)>
<!ELEMENT cuentas (cuentas_ahorro,cuentas_corrientes)>
<!ELEMENT cuentas_ahorro (cuenta_ahorro+)>
<!ELEMENT cuenta_ahorro (balance)>
<!ATTLIST cuenta_ahorro id NMTOKEN #REQUIRED>
<!ATTLIST cuenta_ahorro interes NMTOKEN #REQUIRED>
<!ELEMENT balance (#PCDATA)>
<!ELEMENT cuentas_corrientes (cuenta_corriente+)>
<!ELEMENT cuenta_corriente (balance)>
<!ATTLIST cuenta_corriente id NMTOKEN #REQUIRED>
<!ELEMENT clientes (cliente+)>
<!ELEMENT cliente (nombre,direccion,telefono?)>
<!ATTLIST cliente id NMTOKEN #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT clientes_cuentas (cliente_cuenta+)>
<!ELEMENT cliente_cuenta EMPTY>
<!ATTLIST cliente_cuenta cli_id NMTOKEN #REQUIRED>
<!ATTLIST cliente_cuenta cta_id NMTOKEN #REQUIRED>

=== yagofl02/LDM/xml/Banco.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE banco SYSTEM "Banco.dtd">

<banco>
    <cuentas>
        <cuentas_ahorro>
            <cuenta_ahorro id="a1" interes="0.03">
                <balance>2500</balance>
            </cuenta_ahorro>
            <cuenta_ahorro id="a2" interes="0.03">
                <balance>15075</balance>
            </cuenta_ahorro>
        </cuentas_ahorro>
        <cuentas_corrientes>
            <cuenta_corriente id="a3">
                <balance>4025</balance>
            </cuenta_corriente>
            <cuenta_corriente id="a4">
                <balance>-125</balance>
            </cuenta_corriente>
            <cuenta_corriente id="a5">
                <balance>325</balance>
            </cuenta_corriente>
        </cuentas_corrientes>
    </cuentas>
    <clientes>
        <cliente id="c1">
            <nombre>Juan García</nombre>
            <direccion>Gijón</direccion>
        </cliente>
        <cliente id="c2">
            <nombre>Manuel Sánchez</nombre>
            <direccion>Oviedo</direccion>
            <telefono>612213321</telefono>
        </cliente>
        <cliente id="c3">
            <nombre>Fernando Villa</nombre>
            <direccion>Avilés</direccion>
        </cliente>
    </clientes>
    <clientes_cuentas>
        <cliente_cuenta cli_id="c1" cta_id="a2" />
        <cliente_cuenta cli_id="c1" cta_id="a3" />
        <cliente_cuenta cli_id="c2" cta_id="a4" />
        <cliente_cuenta cli_id="c3" cta_id="a1" />
        <cliente_cuenta cli_id="c3" cta_id="a5" />
    </clientes_cuentas>
</banco>
