=== yagofl02/LDM/xml Tema 1/vivero.dtd
<!ELEMENT vivero (especie+)>
<!ELEMENT especie (nombre,precio,variedad,origen,color_fruto+,otros_datos)>
<!ATTLIST especie siembra NMTOKEN #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ATTLIST precio moneda NMTOKEN #REQUIRED>
<!ELEMENT variedad (#PCDATA)>
<!ELEMENT origen (#PCDATA)>
<!ELEMENT otros_datos (maduración,riego)>
<!ELEMENT riego (#PCDATA)>
<!ELEMENT color_fruto (#PCDATA)>
<!ELEMENT maduración (#PCDATA)>

=== yagofl02/LDM/xml/Ejercicio3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE vivero SYSTEM "vivero.dtd">
<vivero>
    <especie siembra="2018">
        <nombre>Litchi</nombre>
        <precio moneda="euro">25</precio>
        <variedad>Kway May Pink</variedad>
        <origen>Filipinas</origen>
        <color_fruto>rojo</color_fruto>
        <color_fruto>rosa</color_fruto>
        <otros_datos>
            <maduración>agosto</maduración>
            <riego>diario</riego>
        </otros_datos>
    </especie>
    <especie siembra="2018">
        <nombre>Longan</nombre>
        <precio moneda="euro">15</precio>
        <variedad>Champoo</variedad>
        <origen>China</origen>
        <color_fruto>marrón</color_fruto>
        <otros_datos>
            <maduración>octubre</maduración>
            <riego>diario</riego>
        </otros_datos>
    </especie>
    <especie siembra="2016">
        <nombre>Litchi</nombre>
        <precio moneda="euro">21</precio>
        <variedad>Mauritius</variedad>
        <origen>Florida</origen>
        <color_fruto>rojo</color_fruto>
        <otros_datos>
            <maduración>agosto</maduración>
            <riego>diario</riego>
        </otros_datos>
    </especie>
</vivero>
